# Site settings
title: My Little Website
tagline: "this is a tag"
#url: "http://website.com" # hostname & protocol of your web. dns URL

# Social
# socialimg: /img/social.jpg # be sure to change this image
facebook: username
twitter: username
github: username
googleplus: gusername
instagram: gusername

# Contact
phone: "99999999" # This is my real number. You should text me.
email: "yourmail@mail.com" # This is my real email address. Please don't email me.

# Use this for production
#sass:
#    style: compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
# exclude: [.scss, README.md, node_modules, gruntfile.js, package.json, css]
