baseurl: "/Translateme" # the subpath of your site, e.g. /blog
url: "https://jatolentino.github.io" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  keep-history: true
  target-branch: main
